const WateringAction = Object.freeze({
  FETCH_TOTAL_WATERING: "WATERING/TOTAL/FETCH",
  ADD_TOTAL_WATERING: "WATERING/TOTAL/ADD",
  DELETE_ONE_IN_TOTAL_WATERING: "WATERING/TOTAL/DELETE/ONE",
  DELETE_ALL_WATERING: "WATERING/TOTAL/DELETE/ALL",
});

export default WateringAction;
