const AfterWateringCode = Object.freeze({
  SCHEDULE_SHORTEN: "SCHEDULE_SHORTEN",
  NO_CHANGE: "NO_CHANGE",
  SCHEDULE_LENGTHEN: "SCHEDULE_LENGTHEN",
  FIRST_WATERING: "FIRST_WATERING",
  SECOND_WATERING: "SECOND_WATERING",
  INIT_WATERING_PERIOD: "INIT_WATERING_PERIOD",
  NO_RECORD: "NO_RECORD"
})

export default AfterWateringCode;
