const WateringCode = Object.freeze({
  LATE_WATERING: "LATE_WATERING",
  NOT_ENOUGH_RECORD: "NOT_ENOUGH_RECORD",
  THIRSTY: "THIRSTY",
  CHECK: "CHECK",
  RESCHEDULED: "RESCHEDULED",
  LEAVE_HER_ALONE: "LEAVE_HER_ALONE",
  WATERED_TODAY: "WATERED_TODAY",
  YOU_ARE_LAZY: "YOU_ARE_LAZY"
});

export default WateringCode;
