const GardenAction = Object.freeze({
  FETCH_GARDEN: "GARDEN/FETCH",

  FETCH_TODOLIST: "GARDEN/TODO/FETCH",
  UPDATE_TODOLIST: "GARDEN/TODO/UPDATE",
  DELETE_TODOLIST: "GARDEN/TODO/DELETE",

  FETCH_ATTENTION: "GARDEN/ATTENTION/FETCH",
  ADD_ATTENTION: "GARDEN/ATTENTION/ADD",

  FETCH_WAITINGS: "GARDEN/WAITINGS/FETCH",
  DELETE_WAITING: "GARDEN/WAITINGS/DELETE",

  FETCH_ROUTINES: "GARDEN/ROUTINES/FETCH",
  UPDATE_ROUTINES: "GARDEN/ROUTINES/UPDATE",
});

export default GardenAction;
